export interface NutritionInfo {
  servingsPerPackage: number;
  servingSize: string;
  energy: { perServe: string; per100g: string };
  protein: { perServe: string; per100g: string };
  fatTotal: { perServe: string; per100g: string };
  fatSaturated: { perServe: string; per100g: string };
  carbohydrate: { perServe: string; per100g: string };
  sugars: { perServe: string; per100g: string };
  sodium: { perServe: string; per100g: string };
}

export interface Product {
  id: string;
  name: string;
  nativeName?: string;
  subtitle?: string;
  description: string;
  fullDescription?: string;
  category: string;
  image: string;
  sku: string;
  weights: string[];
  price: string;
  origin: string;
  ingredients: string[];
  allergens: string;
  storage: string;
  directions: string[];
  nutrition: NutritionInfo;
  claims: string[];
}

export const PRODUCTS: Product[] = [
  {
    id: "veg-dalle",
    name: "Frozen Dalle Khursani",
    nativeName: "डल्ले खुर्सानी",
    subtitle: "Fireball Cherry Pepper",
    description: "The legendary round peppers of the Himalayas, known for their intense heat and fruity aroma.",
    fullDescription: "Dalle Khursani, or 'Fireball Cherry Peppers', are one of the hottest chilies in the world. Grown in the pristine foothills of the Himalayas, these peppers are characterized by their small, round shape and bright red color. They offer a unique combination of extreme heat and a subtle fruity sweetness that makes them indispensable in Nepalese cuisine. Our Dalle Khursani are flash-frozen at peak ripeness to preserve their flavor, heat, and vibrant color.",
    category: "Frozen vegetables",
    image: "https://images.unsplash.com/photo-1589113103632-f9c644af4722?q=80&w=800&auto=format&fit=crop",
    sku: "NEP-VEG-001",
    weights: ["200g", "300g"],
    price: "12.00",
    origin: "PRODUCT OF NEPAL",
    ingredients: ["Dalle Khursani (Fireball Cherry Pepper)", "Iodised Salt"],
    allergens: "May contain traces of peanuts, tree nuts, sesame, gluten or soy.",
    storage: "Store frozen at -18°C or below.",
    directions: ["Rinse lightly and use in pickles, sauces, or curries", "Can be sliced up and used in salads"],
    nutrition: {
      servingsPerPackage: 30,
      servingSize: "10g",
      energy: { perServe: "20.6kJ", per100g: "206kJ" },
      protein: { perServe: "0.1g", per100g: "1.4g" },
      fatTotal: { perServe: "0g", per100g: "0.4g" },
      fatSaturated: { perServe: "0g", per100g: "0.1g" },
      carbohydrate: { perServe: "0.4g", per100g: "4.2g" },
      sugars: { perServe: "0.4g", per100g: "4.2g" },
      sodium: { perServe: "0mg", per100g: "3mg" }
    },
    claims: ["Halal Certified", "Sustainably Sourced", "No Preservatives Added"]
  },
  {
    id: "veg-green-chilli",
    name: "Frozen Green Chilli",
    nativeName: "हरियो खुर्सानी",
    subtitle: "Hariyo Khursani",
    description: "Crisp and spicy green chilies, hand-picked and frozen to lock in their natural zest.",
    fullDescription: "Our Green Chillies, locally known as 'Hariyo Khursani', are a staple in every Nepalese kitchen. These chilies are picked at the height of their freshness, offering a sharp, clean heat and a bright vegetal flavor. Perfect for spicing up stews, curries, and hand-ground chutneys.",
    category: "Frozen vegetables",
    image: "https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?q=80&w=800&auto=format&fit=crop",
    sku: "NEP-VEG-002",
    weights: ["200g"],
    price: "8.50",
    origin: "PRODUCT OF NEPAL",
    ingredients: ["Green Chilli (Hariyo Khursani)", "Iodised Salt"],
    allergens: "May contain traces of peanuts, tree nuts, sesame, gluten or soy.",
    storage: "Store frozen at -18°C or below.",
    directions: ["Rinse lightly and use in pickles, sauces, or curries", "Can be sliced up and used in salads"],
    nutrition: {
      servingsPerPackage: 30,
      servingSize: "10g",
      energy: { perServe: "18.3kJ", per100g: "183kJ" },
      protein: { perServe: "0.3g", per100g: "2.8g" },
      fatTotal: { perServe: "0g", per100g: "0.3g" },
      fatSaturated: { perServe: "0g", per100g: "0.1g" },
      carbohydrate: { perServe: "0.1g", per100g: "1g" },
      sugars: { perServe: "0.1g", per100g: "1g" },
      sodium: { perServe: "0mg", per100g: "4mg" }
    },
    claims: ["Halal Certified", "Sustainably Sourced", "No Preservatives Added"]
  },
  {
    id: "veg-oyster-mushroom",
    name: "Oyster Mushroom",
    nativeName: "सिपी च्याउ",
    subtitle: "Sipi Chyau",
    description: "Delicate and meaty oyster mushrooms, offering a subtle savory flavor and elegant texture.",
    fullDescription: "Known as 'Sipi Chyau' in Nepal, these oyster mushrooms are celebrated for their velvet-like texture and mild, nutty profile. They are an excellent source of protein and a versatile ingredient for stir-frys, soups, and vegetarian delicacies.",
    category: "Frozen vegetables",
    image: "https://images.unsplash.com/photo-1594315590298-329f49c7dcb9?q=80&w=800&auto=format&fit=crop",
    sku: "NEP-VEG-003",
    weights: ["200g"],
    price: "10.00",
    origin: "PRODUCT OF NEPAL",
    ingredients: ["Oyster Mushroom", "Iodised Salt"],
    allergens: "May contain traces of peanuts, tree nuts, sesame, gluten or soy.",
    storage: "Store frozen at -18°C or below.",
    directions: ["Rinse lightly before use", "Perfect for stir-frys and soups"],
    nutrition: {
      servingsPerPackage: 5,
      servingSize: "60g",
      energy: { perServe: "65.4kJ", per100g: "109kJ" },
      protein: { perServe: "1.9g", per100g: "3.2g" },
      fatTotal: { perServe: "0.1g", per100g: "0.2g" },
      fatSaturated: { perServe: "0g", per100g: "0g" },
      carbohydrate: { perServe: "0.5g", per100g: "0.8g" },
      sugars: { perServe: "0.1g", per100g: "0.2g" },
      sodium: { perServe: "3mg", per100g: "5mg" }
    },
    claims: ["Halal Certified", "Sustainably Sourced", "No Preservatives Added"]
  },
  {
    id: "veg-fiddlehead-fern",
    name: "Fiddle Head Fern",
    nativeName: "नीयूरो",
    subtitle: "Niuro",
    description: "Wild-harvested Himalayan fiddleheads, a seasonal delicacy with a unique earthy snap.",
    fullDescription: "Niuro is a beloved seasonal vegetable in Nepal, foraged from the wild forests of the Himalayas. These tightly curled ferns are rich in antioxidants and offer a flavor profile reminiscent of asparagus and green beans, with an added earthy depth unique to the high altitudes.",
    category: "Frozen vegetables",
    image: "https://images.unsplash.com/photo-1546539782-6fc531453083?q=80&w=800&auto=format&fit=crop",
    sku: "NEP-VEG-004",
    weights: ["200g"],
    price: "15.00",
    origin: "PRODUCT OF NEPAL",
    ingredients: ["Fiddle Head Fern (Niuro)", "Iodised Salt"],
    allergens: "May contain traces of peanuts, tree nuts, sesame, gluten or soy.",
    storage: "Store frozen at -18°C or below.",
    directions: ["Blanch before cooking", "Stir-fry with garlic and cumin"],
    nutrition: {
      servingsPerPackage: 5,
      servingSize: "40g",
      energy: { perServe: "566kJ", per100g: "1410kJ" },
      protein: { perServe: "1.6g", per100g: "3.9g" },
      fatTotal: { perServe: "0.1g", per100g: "0.2g" },
      fatSaturated: { perServe: "0g", per100g: "0g" },
      carbohydrate: { perServe: "30.7g", per100g: "76.7g" },
      sugars: { perServe: "8.2g", per100g: "20.4g" },
      sodium: { perServe: "164mg", per100g: "409mg" }
    },
    claims: ["Wild Harvested", "Sustainably Sourced", "No Preservatives Added"]
  },
  {
    id: "veg-yam",
    name: "Frozen Yam",
    nativeName: "तरुल",
    subtitle: "Tahrul",
    description: "Earthy and nutrient-dense Himalayan yams, pre-cleaned and frozen for convenience.",
    fullDescription: "Tahrul is a staple root vegetable in Nepal, particularly enjoyed during winter festivals. These yams are characterized by their starchy texture and deep, earthy flavor. They are an excellent source of energy and complex carbohydrates.",
    category: "Frozen vegetables",
    image: "https://images.unsplash.com/photo-1596450514735-248ba97ba9fc?q=80&w=800&auto=format&fit=crop",
    sku: "NEP-VEG-005",
    weights: ["500g"],
    price: "11.50",
    origin: "PRODUCT OF NEPAL",
    ingredients: ["Yam (Tahrul)", "Iodised Salt"],
    allergens: "May contain traces of peanuts, tree nuts, sesame, gluten or soy.",
    storage: "Store frozen at -18°C or below.",
    directions: ["Boil until tender", "Use in curries or roast with spices"],
    nutrition: {
      servingsPerPackage: 5,
      servingSize: "100g",
      energy: { perServe: "545kJ", per100g: "545kJ" },
      protein: { perServe: "0.7g", per100g: "0.7g" },
      fatTotal: { perServe: "0.6g", per100g: "0.6g" },
      fatSaturated: { perServe: "0g", per100g: "0g" },
      carbohydrate: { perServe: "28.7g", per100g: "28.7g" },
      sugars: { perServe: "7.6g", per100g: "7.6g" },
      sodium: { perServe: "9mg", per100g: "9mg" }
    },
    claims: ["High Energy", "100% Natural", "No Preservatives Added"]
  },
  {
    id: "veg-hog-plum",
    name: "Hog Plum",
    nativeName: "लप्सी",
    subtitle: "Lapsi ko Dana",
    description: "Unique Himalayan sour plums, widely used for making traditional pickles and candies.",
    fullDescription: "Lapsi is a fruit native to the Nepal Himalayas. It is known for its intense tartness and is the primary ingredient in many beloved Nepalese 'Achar' (pickles) and candies. Frozen to maintain its medicinal properties and sharp flavor profile.",
    category: "Frozen vegetables",
    image: "https://images.unsplash.com/photo-1614730321146-b6fa6a46bac9?q=80&w=800&auto=format&fit=crop",
    sku: "NEP-VEG-006",
    weights: ["350g"],
    price: "13.00",
    origin: "PRODUCT OF NEPAL",
    ingredients: ["Hog Plum (Lapsi ko Dana)", "Iodised Salt"],
    allergens: "May contain traces of peanuts, tree nuts, sesame, gluten or soy.",
    storage: "Store frozen at -18°C or below.",
    directions: ["Wash before use", "Can be consumed raw or used in traditional pickles"],
    nutrition: {
      servingsPerPackage: 10,
      servingSize: "35g",
      energy: { perServe: "57.4kJ", per100g: "164kJ" },
      protein: { perServe: "0.2g", per100g: "0.6g" },
      fatTotal: { perServe: "0g", per100g: "0.1g" },
      fatSaturated: { perServe: "0g", per100g: "0g" },
      carbohydrate: { perServe: "2.3g", per100g: "6.5g" },
      sugars: { perServe: "2.3g", per100g: "6.5g" },
      sodium: { perServe: "1mg", per100g: "2mg" }
    },
    claims: ["Rich in Vitamin C", "Traditional Himalayan Fruit", "No Preservatives Added"]
  },
  {
    id: "veg-pumpkin-shoots",
    name: "Pumpkin Shoots",
    nativeName: "फर्सीको मुन्टा",
    subtitle: "Pharsi ko Munta",
    description: "Tender and nutrient-rich pumpkin vine tips, a traditional farmhouse favorite.",
    fullDescription: "Pharsi ko Munta refers to the young, tender leaves and stems of the pumpkin plant. A classic Nepalese 'Saag', it is prized for its high fiber content and subtle, earthy taste. Our shoots are carefully selected for tenderness before being frozen.",
    category: "Frozen vegetables",
    image: "https://images.unsplash.com/photo-1508748128567-f0a21c02dd54?q=80&w=800&auto=format&fit=crop",
    sku: "NEP-VEG-007",
    weights: ["200g"],
    price: "9.00",
    origin: "PRODUCT OF NEPAL",
    ingredients: ["Pumpkin Shoots (Pharsi ko Munta)"],
    allergens: "May contain traces of peanuts, tree nuts, sesame, gluten or soy.",
    storage: "Store frozen at -18°C or below.",
    directions: ["Stir-fry with garlic", "Steam lightly as a side dish"],
    nutrition: {
      servingsPerPackage: 2,
      servingSize: "100g",
      energy: { perServe: "105kJ", per100g: "105kJ" },
      protein: { perServe: "3g", per100g: "3g" },
      fatTotal: { perServe: "0.3g", per100g: "0.3g" },
      fatSaturated: { perServe: "0g", per100g: "0g" },
      carbohydrate: { perServe: "3.7g", per100g: "3.7g" },
      sugars: { perServe: "1g", per100g: "1g" },
      sodium: { perServe: "5mg", per100g: "5mg" }
    },
    claims: ["High Fiber", "Sustainably Sourced", "No Preservatives Added"]
  },
  {
    id: "veg-bitter-gourd",
    name: "Bitter Gourd",
    nativeName: "करेला",
    subtitle: "Karela",
    description: "Sharp and distinct bitter melon, known for its significant health benefits.",
    fullDescription: "Karela is a staple vegetable across South Asia, valued both for its unique bitter flavor and its numerous medicinal properties, including blood sugar management. Our bitter gourds are sliced and frozen to retain their potency and crunch.",
    category: "Frozen vegetables",
    image: "https://images.unsplash.com/photo-1615484477778-ca3b77940c25?q=80&w=800&auto=format&fit=crop",
    sku: "NEP-VEG-008",
    weights: ["350g"],
    price: "8.00",
    origin: "PRODUCT OF NEPAL",
    ingredients: ["Bitter Gourd (Karela)"],
    allergens: "May contain traces of peanuts, tree nuts, sesame, gluten or soy.",
    storage: "Store frozen at -18°C or below.",
    directions: ["Stir-fry with onions and spices", "Steam as part of a healthy meal"],
    nutrition: {
      servingsPerPackage: 5,
      servingSize: "70g",
      energy: { perServe: "32.9kJ", per100g: "47kJ" },
      protein: { perServe: "0.6g", per100g: "0.9g" },
      fatTotal: { perServe: "0g", per100g: "0g" },
      fatSaturated: { perServe: "0g", per100g: "0g" },
      carbohydrate: { perServe: "0.1g", per100g: "0.2g" },
      sugars: { perServe: "0.1g", per100g: "0.1g" },
      sodium: { perServe: "2mg", per100g: "3mg" }
    },
    claims: ["Medicinal Properties", "100% Natural", "No Preservatives Added"]
  },
  {
    id: "veg-okra",
    name: "Okra",
    nativeName: "भिन्डी",
    subtitle: "Bhindi",
    description: "Tender and versatile okra pods, a favorite for stir-frys and thick stews.",
    fullDescription: "Known as 'Bhindi' in Nepal, our Okra is harvested young to ensure a tender, non-fibrous texture. It is a great source of fiber and vitamins, perfect for quick stir-frys or as a thickening agent in traditional stews.",
    category: "Frozen vegetables",
    image: "https://images.unsplash.com/photo-1614732414444-af9613f3d1a3?q=80&w=800&auto=format&fit=crop",
    sku: "NEP-VEG-009",
    weights: ["350g"],
    price: "8.50",
    origin: "PRODUCT OF NEPAL",
    ingredients: ["Okra (Bhindi)"],
    allergens: "May contain traces of peanuts, tree nuts, sesame, gluten or soy.",
    storage: "Store frozen at -18°C or below.",
    directions: ["Stir-fry on high heat", "Steam lightly"],
    nutrition: {
      servingsPerPackage: 5,
      servingSize: "70g",
      energy: { perServe: "81.2kJ", per100g: "116kJ" },
      protein: { perServe: "2.2g", per100g: "3.1g" },
      fatTotal: { perServe: "0.1g", per100g: "0.2g" },
      fatSaturated: { perServe: "0g", per100g: "0g" },
      carbohydrate: { perServe: "1g", per100g: "1.4g" },
      sugars: { perServe: "1g", per100g: "1.4g" },
      sodium: { perServe: "1mg", per100g: "2mg" }
    },
    claims: ["High Fiber", "Sustainably Sourced", "No Preservatives Added"]
  },
  {
    id: "veg-moringa",
    name: "Moringa Drumstick",
    nativeName: "शीतलचिनी",
    subtitle: "Sitalchini / Sajiwan",
    description: "The ultimate superfood from the Himalayas, rich in protein and essential nutrients.",
    fullDescription: "Moringa, or 'Sitalchini', is often called the 'Miracle Tree'. Our drumsticks are harvested from the fertile plains of Nepal and are packed with vitamins, minerals, and amino acids. A nutrient-dense addition to any soup or curry.",
    category: "Frozen vegetables",
    image: "https://images.unsplash.com/photo-1601004890684-d8cbf393f922?q=80&w=800&auto=format&fit=crop",
    sku: "NEP-VEG-010",
    weights: ["350g"],
    price: "14.00",
    origin: "PRODUCT OF NEPAL",
    ingredients: ["Moringa Drumstick (Sitalchini)"],
    allergens: "May contain traces of peanuts, tree nuts, sesame, gluten or soy.",
    storage: "Store frozen at -18°C or below.",
    directions: ["Add to curries and stews", "Use in soups for added nutrition"],
    nutrition: {
      servingsPerPackage: 3.5,
      servingSize: "100g",
      energy: { perServe: "268kJ", per100g: "268kJ" },
      protein: { perServe: "9.4g", per100g: "9.4g" },
      fatTotal: { perServe: "1.4g", per100g: "1.4g" },
      fatSaturated: { perServe: "0.3g", per100g: "0.3g" },
      carbohydrate: { perServe: "8.3g", per100g: "8.3g" },
      sugars: { perServe: "1.5g", per100g: "1.5g" },
      sodium: { perServe: "25mg", per100g: "25mg" }
    },
    claims: ["Superfood", "High Protein", "No Preservatives Added"]
  },
  {
    id: "veg-ginger",
    name: "Frozen Ginger",
    nativeName: "अदुवा",
    subtitle: "Aduwa",
    description: "Zesty and aromatic Himalayan ginger, pre-cleaned and frozen to maintain its sharp kick.",
    fullDescription: "Our Ginger is grown in the mineral-rich soil of Nepal's hilly regions. It is prized for its high gingerol content, giving it a powerful aroma and a warm, spicy flavor. Essential for both culinary use and traditional wellness teas.",
    category: "Frozen vegetables",
    image: "https://images.unsplash.com/photo-1599940824399-b87987cb5733?q=80&w=800&auto=format&fit=crop",
    sku: "NEP-VEG-011",
    weights: ["200g"],
    price: "7.50",
    origin: "PRODUCT OF NEPAL",
    ingredients: ["Ginger"],
    allergens: "May contain traces of peanuts, tree nuts, sesame, gluten or soy.",
    storage: "Store frozen at -18°C or below.",
    directions: ["Grate into curries", "Add to hot water for tea"],
    nutrition: {
      servingsPerPackage: 10,
      servingSize: "20g",
      energy: { perServe: "26.6kJ", per100g: "133kJ" },
      protein: { perServe: "0.2g", per100g: "0.8g" },
      fatTotal: { perServe: "0.1g", per100g: "0.4g" },
      fatSaturated: { perServe: "0g", per100g: "0.1g" },
      carbohydrate: { perServe: "1g", per100g: "4.8g" },
      sugars: { perServe: "0.3g", per100g: "1.7g" },
      sodium: { perServe: "2mg", per100g: "11mg" }
    },
    claims: ["Natural Digestive", "Aromatic Himalayan Ginger", "No Preservatives Added"]
  },
  {
    id: "veg-garlic",
    name: "Frozen Garlic",
    nativeName: "लसुन",
    subtitle: "Lasun",
    description: "Pungent and flavorful Himalayan garlic cloves, flash-frozen to preserve their nutritional oils.",
    fullDescription: "Grown in high-altitude conditions, our Garlic cloves are smaller and more potent than standard varieties. They offer a deep, robust flavor that forms the foundation of almost every savory Nepalese dish.",
    category: "Frozen vegetables",
    image: "https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?q=80&w=800&auto=format&fit=crop",
    sku: "NEP-VEG-012",
    weights: ["200g"],
    price: "7.00",
    origin: "PRODUCT OF NEPAL",
    ingredients: ["Garlic"],
    allergens: "May contain traces of peanuts, tree nuts, sesame, gluten or soy.",
    storage: "Store frozen at -18°C or below.",
    directions: ["Crush or mince into dishes", "Use in sauces and marinades"],
    nutrition: {
      servingsPerPackage: 10,
      servingSize: "20g",
      energy: { perServe: "105kJ", per100g: "526kJ" },
      protein: { perServe: "1.2g", per100g: "6.1g" },
      fatTotal: { perServe: "0.6g", per100g: "2.8g" },
      fatSaturated: { perServe: "0.1g", per100g: "0.7g" },
      carbohydrate: { perServe: "2g", per100g: "10.2g" },
      sugars: { perServe: "0.3g", per100g: "1.5g" },
      sodium: { perServe: "2mg", per100g: "8mg" }
    },
    claims: ["Immune Support", "Potent Flavor", "No Preservatives Added"]
  },
  {
    id: "veg-bamboo-shoots",
    name: "Young Bamboo Shoots",
    nativeName: "निगालोको टुसा",
    subtitle: "Nigalo ko Tusa",
    description: "Tender and crunchy young bamboo shoots, a Himalayan delicacy for soups and stir-frys.",
    fullDescription: "Nigalo ko Tusa is harvested from the high hills of Nepal. These young shoots have a delicate, slightly sweet flavor and a satisfying crunch. They are a versatile addition to traditional stews and modern Asian cuisine.",
    category: "Frozen vegetables",
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?q=80&w=800&auto=format&fit=crop",
    sku: "NEP-VEG-013",
    weights: ["200g"],
    price: "12.50",
    origin: "PRODUCT OF NEPAL",
    ingredients: ["Young Bamboo Shoots (Nigalo ko Tusa)"],
    allergens: "May contain traces of peanuts, tree nuts, sesame, gluten or soy.",
    storage: "Store frozen at -18°C or below.",
    directions: ["Add to curries and soups", "Stir-fry with aromatics"],
    nutrition: {
      servingsPerPackage: 4,
      servingSize: "50g",
      energy: { perServe: "62.5kJ", per100g: "125kJ" },
      protein: { perServe: "1.3g", per100g: "2.6g" },
      fatTotal: { perServe: "0.2g", per100g: "0.3g" },
      fatSaturated: { perServe: "0g", per100g: "0g" },
      carbohydrate: { perServe: "1.5g", per100g: "3g" },
      sugars: { perServe: "0.9g", per100g: "1.8g" },
      sodium: { perServe: "2mg", per100g: "4mg" }
    },
    claims: ["Low Calorie", "Sustainably Harvested", "No Preservatives Added"]
  },
  {
    id: "veg-rayo-saag",
    name: "Mustard Greens",
    nativeName: "रायो को साग",
    subtitle: "Rayo ko Saag",
    description: "Pungent and nutritious mustard leaves, the heart of traditional Nepalese greens.",
    fullDescription: "Rayo ko Saag is arguably the most famous green in Nepal. It offers a peppery, slightly bitter profile that becomes savory and rich when sautéed. Packed with vitamins and antioxidants, it is a nutritional powerhouse.",
    category: "Frozen vegetables",
    image: "https://images.unsplash.com/photo-1546539782-6fc531453083?q=80&w=800&auto=format&fit=crop",
    sku: "NEP-VEG-014",
    weights: ["200g"],
    price: "9.50",
    origin: "PRODUCT OF NEPAL",
    ingredients: ["Mustard Greens (Rayo ko Saag)"],
    allergens: "May contain traces of peanuts, tree nuts, sesame, gluten or soy.",
    storage: "Store frozen at -18°C or below.",
    directions: ["Stir-fry with garlic and ginger", "Use in soups and stews"],
    nutrition: {
      servingsPerPackage: 4,
      servingSize: "50g",
      energy: { perServe: "47.5kJ", per100g: "95kJ" },
      protein: { perServe: "1.4g", per100g: "2.9g" },
      fatTotal: { perServe: "0.2g", per100g: "0.4g" },
      fatSaturated: { perServe: "0g", per100g: "0g" },
      carbohydrate: { perServe: "0.2g", per100g: "0.3g" },
      sugars: { perServe: "0.1g", per100g: "0.2g" },
      sodium: { perServe: "3mg", per100g: "6mg" }
    },
    claims: ["Rich in Vitamin A", "100% Natural", "No Preservatives Added"]
  },
  {
    id: "veg-bethe-saag",
    name: "Lamb's Quarters",
    nativeName: "बेथे को साग",
    subtitle: "Bethe ko Saag",
    description: "Delicate and mild wild spinach, traditionally foraged for its dense nutrient profile.",
    fullDescription: "Bethe ko Saag is a wild green traditionally foraged in the Nepalese countryside. It has a soft texture and a mild flavor similar to domestic spinach but with much higher concentrations of iron and protein.",
    category: "Frozen vegetables",
    image: "https://images.unsplash.com/photo-1515471204579-f30b050f4a16?q=80&w=800&auto=format&fit=crop",
    sku: "NEP-VEG-015",
    weights: ["350g"],
    price: "10.50",
    origin: "PRODUCT OF NEPAL",
    ingredients: ["Lamb's Quarters (Bethe ko Saag)"],
    allergens: "May contain traces of peanuts, tree nuts, sesame, gluten or soy.",
    storage: "Store frozen at -18°C or below.",
    directions: ["Stir-fry with cumin", "Add to curries"],
    nutrition: {
      servingsPerPackage: 3.5,
      servingSize: "100g",
      energy: { perServe: "180kJ", per100g: "180kJ" },
      protein: { perServe: "4.2g", per100g: "4.2g" },
      fatTotal: { perServe: "0.8g", per100g: "0.8g" },
      fatSaturated: { perServe: "0g", per100g: "0g" },
      carbohydrate: { perServe: "7.3g", per100g: "7.3g" },
      sugars: { perServe: "1g", per100g: "1g" },
      sodium: { perServe: "5mg", per100g: "5mg" }
    },
    claims: ["High Iron", "Wild Foraged", "No Preservatives Added"]
  },
  {
    id: "veg-latte-saag",
    name: "Amaranth Leaves",
    nativeName: "लट्टे को साग",
    subtitle: "Latte ko Saag",
    description: "Vibrant and iron-rich amaranth greens, a staple for a balanced Himalayan diet.",
    fullDescription: "Latte ko Saag, or Amaranth Leaves, is a widely consumed vegetable in Nepal, particularly valued for its high protein and iron content. Its leaves are tender and absorb flavors beautifully in sautéed dishes.",
    category: "Frozen vegetables",
    image: "https://images.unsplash.com/photo-1508748128567-f0a21c02dd54?q=80&w=800&auto=format&fit=crop",
    sku: "NEP-VEG-016",
    weights: ["350g"],
    price: "10.50",
    origin: "PRODUCT OF NEPAL",
    ingredients: ["Amaranth Leaves (Latte ko Saag)"],
    allergens: "May contain traces of peanuts, tree nuts, sesame, gluten or soy.",
    storage: "Store frozen at -18°C or below.",
    directions: ["Stir-fry with onions", "Use in lentil soups"],
    nutrition: {
      servingsPerPackage: 3.5,
      servingSize: "100g",
      energy: { perServe: "96kJ", per100g: "96kJ" },
      protein: { perServe: "2.46g", per100g: "2.46g" },
      fatTotal: { perServe: "0.33g", per100g: "0.33g" },
      fatSaturated: { perServe: "0.091g", per100g: "0.091g" },
      carbohydrate: { perServe: "4.02g", per100g: "4.02g" },
      sugars: { perServe: "1g", per100g: "1g" },
      sodium: { perServe: "20mg", per100g: "20mg" }
    },
    claims: ["Rich in Iron", "100% Natural", "No Preservatives Added"]
  },
  {
    id: "fermented-gundruk",
    name: "Fermented Gundruk",
    nativeName: "गुन्द्रुक",
    subtitle: "Artisanal Himalayan Fermentation",
    description: "Traditional fermented leafy green vegetable. A staple of Himalayan cuisine, offering a unique tangy profile and high probiotic potential.",
    fullDescription: "Gundruk is produced by fermenting leafy vegetables, traditionally mustard, radish, or cauliflower leaves. Our Gundruk is prepared using time-honored artisanal methods, resulting in a complex, sour flavor that serves as the perfect base for traditional soups and pickles. Rich in minerals and natural probiotics, it is a cornerstone of Nepalese wellness and culinary heritage.",
    category: "Fermented",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&q=80",
    sku: "NEP-FER-002",
    weights: ["100g", "250g"],
    price: "14.50",
    origin: "Produced in Nepal. Packaged in Australia.",
    ingredients: ["Fermented Mustard Leaves", "Radish Leaves", "Salt"],
    allergens: "May contain traces of mustard seeds.",
    storage: "Store in a cool, dry place. Once opened, keep in an airtight container.",
    directions: [
      "Soak in warm water for 10 minutes before cooking.",
      "Sauté with garlic, ginger, and tomatoes for a traditional soup.",
      "Can be used as a base for fermented pickles (Achar)."
    ],
    nutrition: {
      servingsPerPackage: 4,
      servingSize: "25g",
      energy: { perServe: "65kJ", per100g: "260kJ" },
      protein: { perServe: "1.2g", per100g: "4.8g" },
      fatTotal: { perServe: "0.2g", per100g: "0.8g" },
      fatSaturated: { perServe: "0.0g", per100g: "0.0g" },
      carbohydrate: { perServe: "1.5g", per100g: "6.0g" },
      sugars: { perServe: "0.4g", per100g: "1.6g" },
      sodium: { perServe: "120mg", per100g: "480mg" }
    },
    claims: ["Probiotic Rich", "High Fiber", "Vegan"]
  },
  {
    id: "momo-01",
    name: "Classic Buffalo Momos",
    nativeName: "बफ मोमो",
    subtitle: "Himalayan Spiced Buffalo Dumplings",
    description: "Traditional buffalo meat dumplings with hand-ground spices.",
    fullDescription: "The crown jewel of Nepalese street food, our Classic Buffalo Momos are made using a time-tested recipe passed down through generations. We use only the finest, lean buffalo meat, seasoned with a secret blend of Himalayan spices, and hand-wrapped in a thin, delicate dough. Each dumpling is a burst of authentic flavor, bringing the taste of Kathmandu's bustling streets directly to your table.",
    category: "Momos",
    image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?q=80&w=800&auto=format&fit=crop",
    sku: "NEP-MOM-001",
    weights: ["500g", "1kg"],
    price: "18.50",
    origin: "Packed in Nepal",
    ingredients: ["Buffalo Meat", "Wheat Flour", "Onion", "Ginger", "Garlic", "Spices"],
    allergens: "Contains Wheat (Gluten). May contain soy.",
    storage: "Store frozen at -18°C or below.",
    directions: ["Steam for 10-12 minutes", "Serve with hot chutney"],
    nutrition: {
      servingsPerPackage: 5,
      servingSize: "100g",
      energy: { perServe: "850kJ", per100g: "850kJ" },
      protein: { perServe: "12g", per100g: "12g" },
      fatTotal: { perServe: "8g", per100g: "8g" },
      fatSaturated: { perServe: "3g", per100g: "3g" },
      carbohydrate: { perServe: "22g", per100g: "22g" },
      sugars: { perServe: "1g", per100g: "1g" },
      sodium: { perServe: "450mg", per100g: "450mg" }
    },
    claims: ["Halal Certified", "No Preservatives"]
  }
];
